from namr.pipeline import _compose_description, FOOTER_MARKER


FOOTER = "Title auto-generated by Claude via namr — https://github.com/jeiros/namr"


def test_empty_description_gets_just_footer():
    assert _compose_description(None, FOOTER) == FOOTER
    assert _compose_description("", FOOTER) == FOOTER
    assert _compose_description("   ", FOOTER) == FOOTER


def test_existing_description_gets_footer_appended():
    result = _compose_description("Felt great today.", FOOTER)
    assert result == f"Felt great today.\n\n{FOOTER}"


def test_existing_description_with_trailing_whitespace_is_trimmed():
    result = _compose_description("Felt great today.\n\n", FOOTER)
    assert result == f"Felt great today.\n\n{FOOTER}"


def test_idempotent_when_marker_already_present():
    desc = f"Some notes.\n\n{FOOTER}"
    assert _compose_description(desc, FOOTER) is None


def test_marker_is_url_substring():
    assert FOOTER_MARKER in FOOTER
