from __future__ import annotations

from pathlib import Path

from pydantic import Field, field_validator
from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    model_config = SettingsConfigDict(env_file=".env", env_file_encoding="utf-8", extra="ignore")

    strava_client_id: str = Field(default="")
    strava_client_secret: str = Field(default="")
    strava_redirect_uri: str = Field(default="http://localhost:8721/callback")

    anthropic_api_key: str = Field(default="")
    namr_model: str = Field(default="claude-sonnet-4-6")

    # LLM backend: "claude_cli" (shells out to `claude -p` — uses your Max
    # plan via CLAUDE_CODE_OAUTH_TOKEN) or "api" (uses ANTHROPIC_API_KEY
    # against api.anthropic.com).
    namr_backend: str = Field(default="claude_cli")
    namr_claude_cli_path: str = Field(default="claude")

    namr_db_path: str = Field(default="data/namr.db")

    namr_poll_interval_seconds: int = 300
    namr_lookback_hours: int = 24
    namr_process_delay_seconds: int = 90
    namr_sports: str = "Run,Ride,TrailRun,VirtualRun,VirtualRide"
    namr_skip_commute: bool = True
    namr_skip_race: bool = True

    namr_dry_run: bool = False
    namr_disabled: bool = False

    # Append an attribution note to each renamed activity's description.
    # The footer is appended only once (idempotent: detected by URL substring).
    namr_append_footer: bool = True
    namr_footer: str = (
        "Title auto-generated by Claude 🤖 — https://github.com/jeiros/namr"
    )

    namr_daily_llm_cap: int = 50

    namr_use_geocode: bool = True
    namr_use_weather: bool = True
    namr_geocode_user_agent: str = "namr/0.1"

    @field_validator("namr_sports")
    @classmethod
    def _strip_sports(cls, v: str) -> str:
        return ",".join(s.strip() for s in v.split(",") if s.strip())

    @property
    def sports(self) -> set[str]:
        return {s for s in self.namr_sports.split(",") if s}

    @property
    def db_path(self) -> Path:
        p = Path(self.namr_db_path)
        p.parent.mkdir(parents=True, exist_ok=True)
        return p


def load_settings() -> Settings:
    return Settings()
